name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: List file
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_ACTION_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
          git clone git@github.com:$GITHUB_ACTION_REPOSITORY
          git checkout $GITHUB_SHA
      - name: List file After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Pavit
      - name: Log Greeting time
        run: echo "${{steps.greet.outputs.time}}"
